In [12]:
from google.colab import files
uploaded = files.upload()

Saving shooping_demo.xls to shooping_demo (2).xls


In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
import pandas as pd

data = pd.read_excel('shooping_demo.xls')
data.head()

Day Discount Free Delivery  Buy
0  Weekday      Yes           Yes  Yes
1  Weekday      Yes           Yes  Yes
2  Weekend       No            No   No
3  Holiday      Yes           Yes  Yes
4  Weekday      Yes           Yes  Yes

In [15]:
data.shape

(50, 4)

In [16]:
data['Buy'].value_counts()

Buy
Yes    41
No      9
Name: count, dtype: int64

In [17]:
PYes = 41/50
PNo = 9/50

In [18]:
print(PYes)

0.82


In [19]:
print(PNo)

0.18


In [ ]:
pd.crosstab(data['Day'], data['Buy'])

Buy      No  Yes
Day             
Holiday   6   18
Weekday   2    9
Weekend   1   14

In [45]:
PHolidayNo = 6/9
PWeekdayNo = 2/9
PWeekendNo = 1/9

PHolidayYes = 18/41
PWeekdayYes = 9/41
PWeekendYes = 14/41

PHoliday = 24/50
PWeekday = 11/50
PWeekend = 15/50

print(PWeekdayYes)


0.21951219512195122


In [ ]:
# P(A|B) ?
# P(B) = PWeekday
# P(A) = No Buy
# P(B|A) = P Weekday/NoBuy

In [46]:
PNoWeekday = (PWeekdayNo*PNo) / PWeekday
print(PNoWeekday)

0.1818181818181818


In [47]:
PYesWeekday = (PWeekdayYes*PYes) / PWeekday
print(PYesWeekday)

0.8181818181818181


In [48]:
# Probabilitas (Buy | Weekday) > dibanding dengan Probabilitas (NoBuy | Weekday)
print(PNoWeekday)
print(PYesWeekday)

0.1818181818181818
0.8181818181818181


In [49]:
# Kondisi B dimana
# Day = Holiday
# Discount = Yes
# Free Delivery = Yes
# A = NoBuy
# P(A|B) = P(NoBuy | DiscountYes, Free Delivery Yes, PDayHoliday)

In [50]:
pd.crosstab(data['Discount'], data['Buy'])

Buy       No  Yes
Discount         
No         5   12
Yes        4   29

In [51]:
PNoDiscountNo = 5/9
PYesDiscountNo = 4/9

PNoDiscountYes = 12/41
PYesDiscountYes = 29/41

PNoDiscount = 17/50
PYesDiscount = 33/50

In [52]:
pd.crosstab(data['Free Delivery'], data['Buy'])

Buy            No  Yes
Free Delivery         
No              4   10
Yes             5   31

In [53]:
PNoDeliveryNo  = 4/9
PYesDeliveryNo = 5/9

PNoDeliveryYes  = 10/41
PYesDeliveryYes = 31/41

PNoDelivery  = 14/50
PYesDelivery = 36/50

In [54]:
# Kondisi B dimana
# Day = Holiday
# Discount = Yes
# Free Delivery = Yes
# P(A) = NoBuy = PNo
# P(B) = PYesDiscount, PYesDelivery, PHoliday
# P(B|A)1 = (PHoliday|No Buy) = PHolidayNo
# P(B|A)2 = (PYesDiscount|No Buy) = PYesDiscountNo
# P(B|A)3 = (PYesDelivery|No Buy) = PYesDeliveryNo
# P(B)1 = PHoliday
# P(B)2 = PYesDiscount
# P(B)3 = PYesDelivery

# ditanyakan P(A|B) ?
# Rumus
# P(A|B) = P(B|A)*P(A)/P(B)

In [55]:
PNoBuy1 = ((PHolidayNo*PYesDiscountNo*PYesDeliveryNo)*PNo)/(PHoliday*PYesDiscount*PYesDelivery)
print(PNoBuy1)

0.12989982125784594


In [56]:
# Kondisi B dimana
# Day = Holiday
# Discount = Yes
# Free Delivery = Yes
# P(A) = Buy = PYes
# P(B) = PYesDiscount, PYesDelivery, PHoliday
# P(B|A)1 = (PHoliday|Buy) = PHolidayYes
# P(B|A)2 = (PYesDiscount|Buy) = PYesDiscountYes
# P(B|A)3 = (PYesDelivery|Buy) = PYesDeliveryYes
# P(B)1 = PHoliday
# P(B)2 = PYesDiscount
# P(B)3 = PYesDelivery

# ditanyakan P(A|B) ?
# Rumus
# P(A|B) = P(B|A)*P(A)/P(B)

In [57]:
PBuy2 = ((PHolidayYes*PYesDiscountYes*PYesDeliveryYes)*PYes)/(PHoliday*PYesDiscount*PYesDelivery)
print(PBuy2)

0.8440667832398943


In [58]:
# probability of No purchase = 0.12989982125784594
# Probability of Purchase = 0.8440667832398943

In [59]:
PSum = PNoBuy1+PBuy2
print(PSum)

0.9739666044977402


In [60]:
PBuy = (PBuy2/PSum)*100
print(PBuy)

86.66280541263185


In [61]:
PNoBuy = (PNoBuy1/PSum)*100
print(PNoBuy)

13.337194587368147


In [62]:
# P(Buy | Day=Weekday, FreeDelivery=Yes, Discount=Yes)

PBuy_a = ((PWeekdayYes * PYesDeliveryYes * PYesDiscountYes) * PYes) / (PWeekday * PYesDelivery * PYesDiscount)
PNoBuy_a = ((PWeekdayNo * PYesDeliveryNo * PYesDiscountNo) * PNo) / (PWeekday * PYesDelivery * PYesDiscount)

PSum_a = PBuy_a + PNoBuy_a

PBuy_a_final = (PBuy_a / PSum_a) * 100
PNoBuy_a_final = (PNoBuy_a / PSum_a) * 100

print("a. P(Buy | Weekday, Yes, Yes)     =", PBuy_a_final)
print("c. P(Not Buy | Weekday, Yes, Yes) =", PNoBuy_a_final)

a. P(Buy | Weekday, Yes, Yes)     = 90.69485518487818
c. P(Not Buy | Weekday, Yes, Yes) = 9.30514481512183


In [63]:
# P(Buy | Day=Weekday, FreeDelivery=No, Discount=No)

PBuy_b = ((PWeekdayYes * PNoDeliveryYes * PNoDiscountYes) * PYes) / (PWeekday * PNoDelivery * PNoDiscount)
PNoBuy_b = ((PWeekdayNo * PNoDeliveryNo * PNoDiscountNo) * PNo) / (PWeekday * PNoDelivery * PNoDiscount)

PSum_b = PBuy_b + PNoBuy_b

PBuy_b_final = (PBuy_b / PSum_b) * 100
PNoBuy_b_final = (PNoBuy_b / PSum_b) * 100

print("b. P(Buy | Weekday, No, No)     =", PBuy_b_final)
print("d. P(Not Buy | Weekday, No, No) =", PNoBuy_b_final)

b. P(Buy | Weekday, No, No)     = 56.54084798345398
d. P(Not Buy | Weekday, No, No) = 43.45915201654603


In [64]:
# P(Buy | Day=Weekend, FreeDelivery=Yes, Discount=Yes)

PBuy_e = ((PWeekendYes * PYesDeliveryYes * PYesDiscountYes) * PYes) / (PWeekend * PYesDelivery * PYesDiscount)
PNoBuy_e = ((PWeekendNo * PYesDeliveryNo * PYesDiscountNo) * PNo) / (PWeekend * PYesDelivery * PYesDiscount)

PSum_e = PBuy_e + PNoBuy_e

PBuy_e_final = (PBuy_e / PSum_e) * 100
PNoBuy_e_final = (PNoBuy_e / PSum_e) * 100

print("e. P(Buy | Weekend, Yes, Yes)     =", PBuy_e_final)
print("g. P(Not Buy | Weekend, Yes, Yes) =", PNoBuy_e_final)

e. P(Buy | Weekend, Yes, Yes)     = 96.80747821165603
g. P(Not Buy | Weekend, Yes, Yes) = 3.1925217883439725


In [65]:
# P(Buy | Day=Weekend, FreeDelivery=No, Discount=No)

PBuy_f = ((PWeekendYes * PNoDeliveryYes * PNoDiscountYes) * PYes) / (PWeekend * PNoDelivery * PNoDiscount)
PNoBuy_f = ((PWeekendNo * PNoDeliveryNo * PNoDiscountNo) * PNo) / (PWeekend * PNoDelivery * PNoDiscount)

PSum_f = PBuy_f + PNoBuy_f

PBuy_f_final = (PBuy_f / PSum_f) * 100
PNoBuy_f_final = (PNoBuy_f / PSum_f) * 100

print("f. P(Buy | Weekend, No, No)     =", PBuy_f_final)
print("h. P(Not Buy | Weekend, No, No) =", PNoBuy_f_final)

f. P(Buy | Weekend, No, No)     = 80.18856806128463
h. P(Not Buy | Weekend, No, No) = 19.811431938715383


In [66]:
import pandas as pd

hasil = {
    "Kasus": [
        "a. P(Buy | Weekday, Yes, Yes)",
        "b. P(Buy | Weekday, No, No)",
        "c. P(Not Buy | Weekday, Yes, Yes)",
        "d. P(Not Buy | Weekday, No, No)",
        "e. P(Buy | Weekend, Yes, Yes)",
        "f. P(Buy | Weekend, No, No)",
        "g. P(Not Buy | Weekend, Yes, Yes)",
        "h. P(Not Buy | Weekend, No, No)"
    ],
    "Probabilitas (%)": [
        90.69, 56.54, 9.31, 43.46, 96.81, 80.19, 3.19, 19.81
    ]
}

df = pd.DataFrame(hasil)
df


Kasus  Probabilitas (%)
0      a. P(Buy | Weekday, Yes, Yes)             90.69
1        b. P(Buy | Weekday, No, No)             56.54
2  c. P(Not Buy | Weekday, Yes, Yes)              9.31
3    d. P(Not Buy | Weekday, No, No)             43.46
4      e. P(Buy | Weekend, Yes, Yes)             96.81
5        f. P(Buy | Weekend, No, No)             80.19
6  g. P(Not Buy | Weekend, Yes, Yes)              3.19
7    h. P(Not Buy | Weekend, No, No)             19.81

Kesimpulan

Berdasarkan perhitungan Naive Bayes menggunakan dataset shopping_demo.xls, dapat disimpulkan bahwa:
*   Peluang pembelian meningkat signifikan saat Discount = Yes dan Free Delivery = Yes, baik pada Weekday (90.69%) maupun Weekend (96.81%).
*   Ketika tidak ada diskon dan tidak ada free delivery, peluang pembelian menurun cukup tajam — hanya sekitar 56.54% pada Weekday dan 80.19% pada Weekend.
*  Faktor hari (Weekday atau Weekend) memberikan sedikit pengaruh, namun faktor promosi (diskon dan gratis ongkir) jauh lebih dominan dalam menentukan keputusan pembelian.
*  Peluang “Not Buy” paling kecil juga muncul saat pelanggan mendapatkan diskon dan gratis ongkir pada Weekend (3.19%), menunjukkan bahwa kombinasi promosi ini sangat efektif.

Dengan demikian, strategi promosi yang paling efektif untuk meningkatkan pembelian adalah memberikan diskon dan free delivery secara bersamaan, terutama pada akhir pekan (Weekend) ketika minat belanja pelanggan sedang tinggi.
